# Generated by Django 3.2.4 on 2021-07-08 19:35

import car.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=128, null=True)),
                ('car_model_name', models.CharField(blank=True, max_length=128, null=True)),
                ('seats', models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('car_type', models.CharField(blank=True, max_length=128, null=True)),
                ('fuel', models.CharField(blank=True, max_length=16, null=True)),
                ('rent', models.FloatField(blank=True, null=True)),
                ('number_plate', models.CharField(error_messages={'unique': 'Car exist in database already.'}, max_length=16, unique=True)),
                ('issue', models.TextField(blank=True, error_messages={'max_length': 'message length must be less then 250'}, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('drop_address', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(blank=True, null=True)),
                ('available_from', models.DateField(default=datetime.date(2021, 7, 8))),
                ('availability_ends', models.DateField(default=datetime.date(2021, 7, 8))),
                ('AC', models.BooleanField()),
                ('AorM', models.BooleanField()),
                ('front_image', models.ImageField(blank=True, null=True, upload_to=car.models.content_file_name)),
                ('buying_year', models.IntegerField(default=2021)),
                ('mileage', models.FloatField(default=24)),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True, max_length=30, null=True)),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_on', models.DateField(default=datetime.date(2021, 7, 8))),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('renterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model_name', models.CharField(blank=True, max_length=128, null=True)),
                ('payable_amount', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booked_on', models.DateField()),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_ownerId', to=settings.AUTH_USER_MODEL)),
                ('renterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_renterId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
