# Generated by Django 3.2.4 on 2021-07-01 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='booked_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 19, 38, 14, 596173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booked',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 19, 38, 14, 596173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cancel',
            name='cancelled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 19, 38, 14, 596173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='car',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 19, 38, 14, 596173, tzinfo=utc)),
        ),
    ]
