# Generated by Django 3.2.4 on 2021-07-02 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20210702_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='booked_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 16, 40, 55, 764322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booked',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 16, 40, 55, 764322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cancel',
            name='cancelled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 16, 40, 55, 764322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='car',
            name='availability_ends',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='available_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 2, 16, 40, 55, 764322, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='company',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='drop_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='rc_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='rent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
