# Generated by Django 3.2.4 on 2021-07-03 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20210703_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='car_model_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='car_model_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='booked',
            name='booked_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 9, 34, 52, 79132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booked',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 9, 34, 52, 79132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cancel',
            name='cancelled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 9, 34, 52, 79132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='car',
            name='available_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 3, 9, 34, 52, 79132, tzinfo=utc), null=True),
        ),
    ]
