# Generated by Django 3.2.4 on 2021-07-09 08:27

import car.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20210709_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to=car.models.content_file_name('car_back/')),
        ),
        migrations.AlterField(
            model_name='car',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to=car.models.content_file_name('car_front/')),
        ),
    ]
