# Generated by Django 3.2.4 on 2021-07-03 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20210703_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='booked_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 9, 58, 32, 309854, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booked',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 9, 58, 32, 309854, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cancel',
            name='cancelled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 9, 58, 32, 309854, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='car',
            name='available_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 3, 9, 58, 32, 309854, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='number_plate',
            field=models.CharField(error_messages={'unique': 'Car exist in database already.'}, max_length=16, unique=True),
        ),
    ]
