# Generated by Django 3.2.4 on 2021-07-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_remove_cancel_carid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancel',
            name='bookId',
        ),
    ]
