# Generated by Django 3.2.4 on 2021-07-10 04:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.content_file_name('profile_photo/')),
        ),
    ]
