# Generated by Django 3.2.4 on 2021-07-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210710_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='license',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
